ingress:
  globalStaticIpName: blog-production
  hostname: blog.sourced.tech
nodeSelector:
  cloud.google.com/gke-nodepool: default-pool
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
       matchExpressions:
        - key: app
          operator: In
          values:
       #if the chart name is changed or a nameOverride is used, this value has to be changed to the new name.
              - blog
      topologyKey: kubernetes.io/hostname
